name: Create CNAME file

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  create-cname:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3